// packages/svelte/src/components/TextField/TextField.svelte
<script lang="ts">
    import type { TextFieldVariants } from "@scottylabs/variants";
    import { textField } from "@scottylabs/variants";
    import type { Snippet } from "svelte";
    import type { HTMLInputAttributes } from "svelte/elements";

    type Props = Omit<HTMLInputAttributes, "size"> &
        TextFieldVariants & {
            trailingIcon?: Snippet;
        };

    let {
        intent,
        fieldStyle,
        size,
        trailingIcon,
        class: className,
        ...rest
    }: Props = $props();

    const cls = $derived(String(textField({ intent, fieldStyle, size, class: className as string | undefined })));
</script>

{#if trailingIcon}
    <div class="sl-text-field-wrapper">
        <input class={cls} {...rest} />
        <span class="sl-text-field-trailing-icon">{@render trailingIcon()}</span>
    </div>
{:else}
    <input class={cls} {...rest} />
{/if}

// packages/react/src/components/TextField/index.tsx
import { type TextFieldVariants, textField } from "@scottylabs/variants";
import { forwardRef, type InputHTMLAttributes, type ReactNode } from "react";

export interface TextFieldProps
    extends Omit<InputHTMLAttributes<HTMLInputElement>, "size">, TextFieldVariants {
    trailingIcon?: ReactNode;
}

export const TextField = forwardRef<HTMLInputElement, TextFieldProps>(function TextField(
    { intent, fieldStyle, size, trailingIcon, className, ...rest },
    ref,
) {
    const cls = textField({ intent, fieldStyle, size, class: className });

    if (trailingIcon) {
        return (
            <div className="sl-text-field-wrapper">
                <input ref={ref} className={cls} {...rest} />
                <span className="sl-text-field-trailing-icon">{trailingIcon}</span>
            </div>
        );
    }

    return <input ref={ref} className={cls} {...rest} />;
});
