// packages/react/src/components/Button/index.tsx
import { Slot } from "@radix-ui/react-slot";
import { type ButtonHTMLAttributes, forwardRef } from "react";
import { button, type ButtonVariants } from "@scottylabs/variants";

export interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement>, ButtonVariants {
    asChild?: boolean;
}

export const Button = forwardRef<HTMLButtonElement, ButtonProps>(function Button(
    { intent, variant, size, asChild, className, ...rest },
    ref,
) {
    const Comp = asChild ? Slot : "button";
    const cls = button({ intent, variant, size, class: className });
    return <Comp ref={ref} className={cls} {...rest} />;
});

// packages/svelte/src/components/Button/Button.svelte
<script lang="ts">
    import type { Snippet } from "svelte";
    import type { HTMLButtonAttributes } from "svelte/elements";
    import { button } from "@scottylabs/variants";
    import type { ButtonVariants } from "@scottylabs/variants";

    type Props = HTMLButtonAttributes &
        ButtonVariants & {
            children?: Snippet;
            child?: Snippet<[{ class: string }]>;
        };

    let {
        intent,
        variant,
        size,
        children,
        child,
        class: className,
        ...rest
    }: Props = $props();

    const cls = $derived(String(button({ intent, variant, size, class: className as string | undefined })));
</script>

{#if child}
    {@render child({ class: cls })}
{:else}
    <button class={cls} {...rest}>
        {@render children?.()}
    </button>
{/if}
